config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index] do
    resources :achievement do
      post "/redeem_extra_fuel" => "achievements#redeem_extra_fuel"
      post "/redeem_fast_travel" => "achievements#redeem_fast_travel"
      post "/redeem_gotta_go_fast" => "achievements#redeem_gotta_go_fast"
    end
  end
  resources :projects, only: [:index, :show] do
    resources :sprints do
      resources :tickets, only: [:create, :update, :delete] do
        post "/next" => "tickets#next"
        post "/previous" => "tickets#previous"
        resources :reviews, only: [:create]
      end
    end
  end
  root 'welcome#show'
end

app/models/user.rb
require 'faker'

class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable
  validates :first_name, :last_name, :level, :xp, presence: true
  has_many :tickets
  has_many :projects
  has_many :achievements

  before_validation :give_anonyme_name
  after_create :create_achievements

  def gain_xp(gained_xp)
    prior_xp = xp
    self.xp += gained_xp * self.multiplier
    while self.xp >= next_lvl_xp_goal
      self.level += 1
    end
    save!
    update_user_tendencys(xp, prior_xp)
  end

  def company_rank
    User.order(xp: :desc).index(self) + 1
  end

  def next_lvl_xp_goal
    if self.level == 0
      10
    else
      self.level * 25
    end
  end

  def previous_lvl_xp_goal
    if self.level == 0
      0
    elsif self.level == 1
      10
    else
      (self.level-1) * 25
    end
  end

  def percent_of_current_level
    ((self.xp-previous_lvl_xp_goal).to_f/(next_lvl_xp_goal-previous_lvl_xp_goal)*100)
  end

  def create_achievements
    return if self.achievements.any?
    self.achievements.create(name:'Gotta go fast', description: '2x Points for 24h', points:0, goal:1)
    self.achievements.create(name:'Fast travel', description: 'Jump to the next level', points:0, goal:2)
    self.achievements.create(name:'Extra fuel', description: 'Recive 45xp', points:0, goal:2)
  end

  private

  def give_anonyme_name
    self.first_name ||= Faker::Color.color_name
    self.last_name ||= Faker::Creature::Animal.name
  end

  def update_user_tendencys(new_xp, prior_xp)
    lower_xp = new_xp - 1
    if User.where(xp: (prior_xp..lower_xp)).any?
      self.tendency = 0
    else
      User.where(xp: (prior_xp..lower_xp)).each do |user|
        user.tendency = -1
        user.save!
      end
      self.tendency = 1
    end
    save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show; end

  def index
    @factory = User.order(xp: :desc)
  end
end

app/views/users/_completed_achievement.html.erb
<div class="alert alert-success" role="alert">
  <div class="row">
    <div class="col-3">
      <%= render partial: 'shared/achivement_image_helper', locals: { name: achievement.name } %>
    </div>
    <div class="col">
      <div class="row">
        <div class="col">
          <b><%= achievement.name %></b>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= achievement.description %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= render partial: 'redeem_achievement_button', locals: { name: achievement.name, achievement_id: achievement.id } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_redeem_achievement_button.html.erb
<% if name == 'Gotta go fast' %>
    <%= link_to 'Redeem', user_achievement_redeem_gotta_go_fast_path(user_id: current_user.id,
                                                                     achievement_id: achievement_id), method: :post, class:'btn btn-success'%>
<% elsif name == 'Fast travel' %>
  <%= link_to 'Redeem', user_achievement_redeem_fast_travel_path(user_id: current_user.id,
                                                                achievement_id: achievement_id), method: :post, class:'btn btn-success'%>
<% elsif name == 'Extra fuel' %>
  <%= link_to 'Redeem', user_achievement_redeem_extra_fuel_path(user_id: current_user.id,
                                                                achievement_id: achievement_id), method: :post, class:'btn btn-success'%>
<% end %>

app/views/users/_redeemed_achievement.html.erb
<div class="alert alert-secondary" role="alert">
  <div class="row">
    <div class="col-3">
      <%= render partial: 'shared/achivement_image_helper', locals: { name: achievement.name } %>
    </div>
    <div class="col">
      <div class="row">
        <div class="col">
          <b><%= achievement.name %></b>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= achievement.description %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <span class="badge badge-pill badge-secondary">Redeemed</span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_tendency_indicator.html.erb
<% if tendency == 1 %>
  <%= fa_icon('angle-up') %>
<% elsif tendency == -1 %>
  <%= fa_icon('angle-down') %>
<% end %>

app/views/users/_uncomplete_achievement.html.erb
<div class="alert alert-warning" role="alert">
  <div class="row">
    <div class="col-3">
      <%= render partial: 'shared/achivement_image_helper', locals: {name: achievement.name } %>
    </div>
    <div class="col">
      <div class="row">
        <div class="col">
          <b><%= achievement.name %></b>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= achievement.description %>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <div class="progress" style="background-color: #abb;">
            <div class="progress-bar bg-info" role="progressbar" style="width: <%= achievement.current_percent %>%;" aria-valuenow="<%= achievement.points %>" aria-valuemin="0" aria-valuemax="<%= achievement.goal %>">
              <%= achievement.points %>/<%= achievement.goal%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<div class="row">
  <div class="col-8">
    <%= user.first_name %>
    <%= user.last_name %>
    (<%= user.xp %>xp)
  </div>
  <div class="col-2">
    #<%= user.company_rank %>
  </div>
  <div class="col-2">
    <%= render partial: 'tendency_indicator', locals: { tendency: user.tendency } %>
  </div>
</div>

app/views/users/_user_achievements.html.erb
<div class="card text-white bg-info">
  <div class="card-header">Achievements</div>
  <div class="card-body">
    <div class="row">
      <div class="col">
          <% current_user.achievements.each do |achievement| %>
            <% if achievement.completed? %>
              <%= render partial: 'completed_achievement', locals: { achievement: achievement } %>
            <% elsif achievement.redeemed? %>
              <%= render partial: 'redeemed_achievement', locals: { achievement: achievement } %>
            <% else%>
              <%= render partial: 'uncomplete_achievement', locals: { achievement: achievement } %>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="card text-white bg-dark">
      <div class="card-header">Scoreboard</div>
        <div class="col">
          <% @factory.each do |user| %>
            <div class="alert alert-dark" role="alert">
              <%= render partial: 'user', locals: { user: user } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="card text-white bg-dark">
      <div class="card-header">Profil</div>
      <div class="card-body">
        <div class="row">
          <div class="col">
            <h3 class="card-title"><%= current_user.first_name %> <%= current_user.last_name %></h3>
          </div>
            <%= render partial: 'shared/level_indicator' %>
          <div class="col">
          </div>
        </div>
        <p class="card-text">
          <div class="row">
            <div class="col-8">
              <%= image_tag 'default_image.jpg', style: 'height: 250px; border-radius: 150px; margin-bottom: 30px; margin-top: 10px;' %>
            </div>
            <div class="col-4">
            </div>
          </div>
          <div class="row">
            <div class="col">
              <ul class="list-group">
                <li class="list-group-item list-group-item-info">
                  <div class="row">
                    <div class="col">All points:</div>
                    <div class="col"><%= current_user.xp %></div>
                  </div>
                </li>
                <li class="list-group-item list-group-item-info">
                  <div class="row">
                    <div class="col">Points in this level:</div>
                    <div class="col"><%= current_user.xp - current_user.previous_lvl_xp_goal %></div>
                  </div>
                </li>
                <li class="list-group-item list-group-item-info">
                  <div class="row">
                    <div class="col">Points to next level:</div>
                    <div class="col"><%= current_user.next_lvl_xp_goal - current_user.xp %></div>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </p>
      </div>
    </div>
    <br>
    <%= render partial: 'user_achievements.html.erb' %>
  </div>
</div>