config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index] do
    resources :achievement do
      post "/redeem_extra_fuel" => "achievements#redeem_extra_fuel"
      post "/redeem_fast_travel" => "achievements#redeem_fast_travel"
      post "/redeem_gotta_go_fast" => "achievements#redeem_gotta_go_fast"
    end
  end
  resources :projects, only: [:index, :show] do
    resources :sprints do
      resources :tickets, only: [:create, :update, :delete] do
        post "/next" => "tickets#next"
        post "/previous" => "tickets#previous"
        resources :reviews, only: [:create]
      end
    end
  end
  root 'welcome#show'
end

app/views/shared/_achivement_image_helper.html.erb
<% if name == 'Gotta go fast' %>
  <%= fa_icon('forward', class: "fa-5x") %>
<% elsif name == 'Fast travel' %>
  <%= fa_icon('map', class: "fa-5x") %>
<% elsif name == 'Extra fuel' %>
  <%= fa_icon('battery-full', class: "fa-5x") %>
<% end %>

app/views/shared/_level_indicator.html.erb
<h5><span class="badge badge-pill badge-warning" style="position: absolute;right: 5px; margin-right: 25px" >Level:<%= current_user.level %></span></h5>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark">
  <%= link_to 'Gameban', root_path, class:'navbar-brand' %>
<% if current_user.blank? %>
  </nav>
<% else %>
    <%= link_to 'Project Board', projects_path, class:'navbar-brand' %>
    <%= link_to 'Scoreboard', users_path, class:'navbar-brand' %>
    <div>
      <%= image_tag 'default_image.jpg', style: 'height: 35px; border-radius: 35px;' %>
      <%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user), class:'navbar-brand' %>
      <%= link_to fa_icon("sign-out"), destroy_user_session_path, method: :delete, class:'navbar-brand' %>
    </div>
  </nav>
    </nav>
    <%= render partial: 'shared/xp_bar'   %>
<% end %>

app/views/shared/_xp_bar.html.erb
<div class="progress" style="background-color: #aba; height: 25px;">
  <div class="progress-bar bg-success" role="progressbar" style="width: <%= current_user.percent_of_current_level %>%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="<%= current_user.next_lvl_xp_goal %>>">
    <%= current_user.xp - current_user.previous_lvl_xp_goal  %>xp/<%= current_user.next_lvl_xp_goal - current_user.previous_lvl_xp_goal %>xp
  </div>
  <%= render partial: 'shared/level_indicator' %>
</div>