config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index] do
    resources :achievement do
      post "/redeem_extra_fuel" => "achievements#redeem_extra_fuel"
      post "/redeem_fast_travel" => "achievements#redeem_fast_travel"
      post "/redeem_gotta_go_fast" => "achievements#redeem_gotta_go_fast"
    end
  end
  resources :projects, only: [:index, :show] do
    resources :sprints do
      resources :tickets, only: [:create, :update, :delete] do
        post "/next" => "tickets#next"
        post "/previous" => "tickets#previous"
        resources :reviews, only: [:create]
      end
    end
  end
  root 'welcome#show'
end

app/models/sprint.rb
class Sprint < ApplicationRecord
  belongs_to :project
  has_many :tickets

  validate :different_qualities?
  validates :project_id, :start_time, :length, presence: true
  validates :quality_1, :quality_2, :quality_3, :quality_4, :quality_5, presence: true

  def code_qualeties
    [self.quality_1, self.quality_2, self.quality_3, self.quality_4, self.quality_5]
  end

  private

  def different_qualities?
    unless code_qualeties.uniq.length == 5
      errors.add(:code_qualeties, 'two or more qualities are the same')
    end
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  def new
    @project = Project.find(params[:project_id])
    @sprint = @project.sprints.build
  end

  def create
    @project = Project.find(params[:project_id])
    @sprint = @project.sprints.build(sprint_params)
    if @sprint.save
      flash[:success] = 'Sprint has been created'
      redirect_to project_sprints_path
    else
      flash[:alert] = 'Sprint could not be created'
      render 'new'
    end
  end

  def index
    @project = Project.find(params[:project_id])
    @sprints = Sprint.where(project_id: params[:project_id])
  end

  def edit
    @project = Project.find(params[:project_id])
    @sprint = Sprint.find(params[:id])
  end

  def update
    @sprint = Sprint.find(params[:id])
    @project = Project.find(@sprint.project_id)
    if @sprint.update(sprint_params)
      flash[:success] = 'Sprint has been updated'
      redirect_to project_sprints_path(@project.id)
    else
      flash.now[:error] = 'Sprint could not be updated'
      render :edit
    end
  end

  private

  def sprint_params
    params.require(:sprint).permit(:project_id,
                                   :start_time,
                                   :length,
                                   :quality_1,
                                   :quality_2,
                                   :quality_3,
                                   :quality_4,
                                   :quality_5,)
  end
end

app/views/sprints/edit.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="card text-white bg-dark">
      <div class="card-header"><h5>Edit Sprint</h5></div>
  <div class="card-body">
    <%= simple_form_for @sprint, url: project_sprint_path(@project, @sprint) do |f| %>
      <% f.input :project_id, html: { input: @project.id }, as: :hidden %>
      <div class="row">
        <div class="col">
          <p>When will the Sprint begin?</p>
          <%= f.input :start_time, as: :date, label: false %>
          <br></br>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p>How long will the Sprint be?</p>
          <%= f.collection_radio_buttons(:length,
                                         [[1, 'a week'] ,[2, 'two weeks'], [3, 'three weeks']],
                                         :first,
                                         :last) { |a| a.radio_button + " " + a.label + " " } %>
          <br></br>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p>Welche fünf individuelle Codequalitäten sollen verbessert werden?</p>
          <%= f.input :quality_1, label: false, placeholder: '(e.g. Security)' %>
          <%= f.input :quality_2, label: false, placeholder: '(e.g. Understandability)' %>
          <%= f.input :quality_3, label: false, placeholder: '(e.g. Time behaviour)' %>
          <%= f.input :quality_4, label: false, placeholder: '(e.g. Analyzability)' %>
          <%= f.input :quality_5, label: false, placeholder: '(e.g. Recoverability)' %>
        </div>
      </div>
      <%= f.submit 'Save', class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

app/views/sprints/index.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="card text-white bg-dark">
      <div class="card-header">
        <div class="row">
          <div class="col-10"><h5>Sprints for: <%= @project.name %></h5></div>
          <div class="col"><%= link_to fa_icon('plus'), new_project_sprint_path(@project), class: 'btn btn-info'   %></div>
        </div>
      </div>
        <div class="card-body">
          <ul class="list-group text-dark">
            <% @sprints.each do |sprint| %>
              <li class="list-group-item">
                <div class="row">
                  <div class="col-10">
                    <%= sprint.start_time %>
                     until
                    <%= sprint.start_time + sprint.length.weeks %>
                  </div>
                  <div class="col-1"><%= link_to fa_icon('edit'), edit_project_sprint_path(id: sprint.id), class: 'btn btn-info' %></div>
                </div>
              </li>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/sprints/new.html.erb
<div class="row">
  <div class="col-4 offset-4">
    <div class="card text-white bg-dark">
      <div class="card-header"><h5>Create Sprint</h5></div>
  <div class="card-body">
    <%= simple_form_for @sprint, url: project_sprints_path do |f| %>
      <% f.input :project_id, html: { input: @project.id }, as: :hidden %>
      <div class="row">
        <div class="col">
          <p>When will the Sprint begin?</p>
          <%= f.input :start_time, as: :date, label: false %>
          <br></br>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p>How long will the Sprint be?</p>
          <%= f.collection_radio_buttons(:length,
                                         [[1, 'a week'] ,[2, 'two weeks'], [3, 'three weeks']],
                                         :first,
                                         :last) { |a| a.radio_button + " " + a.label + " " } %>
          <br></br>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <p>Welche fünf individuelle Codequalitäten sollen verbessert werden?</p>
          <%= f.input :quality_1, label: false, placeholder: '(e.g. Security)' %>
          <%= f.input :quality_2, label: false, placeholder: '(e.g. Understandability)' %>
          <%= f.input :quality_3, label: false, placeholder: '(e.g. Time behaviour)' %>
          <%= f.input :quality_4, label: false, placeholder: '(e.g. Analyzability)' %>
          <%= f.input :quality_5, label: false, placeholder: '(e.g. Recoverability)' %>
        </div>
      </div>
      <%= f.submit 'Save', class: 'btn btn-info' %>
    <% end %>
  </div>
</div>