config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :index] do
    resources :achievement do
      post "/redeem_extra_fuel" => "achievements#redeem_extra_fuel"
      post "/redeem_fast_travel" => "achievements#redeem_fast_travel"
      post "/redeem_gotta_go_fast" => "achievements#redeem_gotta_go_fast"
    end
  end
  resources :projects, only: [:index, :show] do
    resources :sprints do
      resources :tickets, only: [:create, :update, :delete] do
        post "/next" => "tickets#next"
        post "/previous" => "tickets#previous"
        resources :reviews, only: [:create]
      end
    end
  end
  root 'welcome#show'
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  STATUSES = ['Backlog', 'Todo', 'In progress', 'Quality Assurance', 'Done']
  PRIORITIES = ['Critical', 'Major', 'Normal', 'Low']

  validates :name, :description, presence: true
  validates :priority, inclusion: { in: PRIORITIES }
  validates :status, inclusion: { in: STATUSES }
  belongs_to :sprint
  belongs_to :user, optional: true
  has_many :review

  def next_status
    new_status = STATUSES[STATUSES.index(self.status) + 1]
    complete_ticket(self.priority) if new_status == 'Done'
    return if new_status == nil

    self.status = new_status
    save!
  end

  def previous_status
    new_status = STATUSES[STATUSES.index(self.status) - 1]
    return if new_status == nil

    self.status = new_status
    save!
  end

  private

  def complete_ticket(priority)
    priority_faktor = {
      'Critical' => 3,
      'Major' => 2,
      'Normal' => 1,
      'Low' => 1
    }
    points = priority_faktor[priority] * 2
    self.user.gain_xp(points)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def create
    @sprint = Sprint.find(params[:sprint_id])
    ticket = @sprint.tickets.build(ticket_params)
    ticket.user_id = current_user.id
    if ticket.save
      extra_fuel_achievement = Achievement.where(user_id: current_user.id, name: 'Extra fuel').first
      unless extra_fuel_achievement.completed?
        extra_fuel_achievement.add_point
        flash[:notice] = 'Achievement unlocked! Check your Profile' if extra_fuel_achievement.completed?
      end
    else
      flash[:alert] = 'Ticket could not be created'
    end
    redirect_to project_path(params[:project_id])
  end

  def update
    ticket = Ticket.find(params[:id])
    if ticket.update(ticket_params)
      redirect_to project_path(params[:project_id])
    else
      flash[:alert] = 'Ticket could not be updated'
      redirect_to project_path(params[:project_id])
    end
  end

  def next
    ticket = Ticket.find(params[:ticket_id])
    ticket.next_status
    redirect_to project_path(ticket.sprint.project)
  end

  def previous
    ticket = Ticket.find(params[:ticket_id])
    ticket.previous_status
    redirect_to project_path(ticket.sprint.project)
  end

  private

  def ticket_params
    params.require(:ticket).permit(:name,
                                   :description,
                                   :hours_of_work,
                                   :priority,
                                   :status)
  end
end

app/views/tickets/_card.html.erb
<div class="row">
  <div class="col-12">
    <a class="card" href='#editTicket' data-toggle="modal" data-target="#createModal<%= ticket.id %>">
      <div class="card-body text-dark">
        <div class="card-title">
          <div class="row">
            <div class="col-8">
              <b><%= ticket.name %></b>
            </div>
            <div class="col-3">
              <div class="row">
                <%= render partial: 'tickets/prioritie_badge', locals: { priority: ticket.priority } %>
              </div>
              <div class="row">
                Hours: <%= ticket.hours_of_work %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>

<%= render partial: 'tickets/edit_modal', locals: { ticket: ticket } %>

app/views/tickets/_column.html.erb
<div class="card text-white bg-dark mb-3" style="max-width: 25rem;">
  <div class="card-header">
    <h5 class="card-title">
      <%= status %>
    </h5>
  </div>
  <div class="card-body">
    <% project.get_column_tickets(status).each do |ticket| %>
      <% if status == 'Quality Assurance' %>
        <%= render partial: 'tickets/qa_card', locals: { ticket: ticket } %>
      <% elsif status == 'Done' %>
        <%= render partial: 'tickets/done_card', locals: { ticket: ticket } %>
      <% else %>
        <%= render partial: 'tickets/card', locals: { ticket: ticket } %>
      <% end %>
      <br>
    <% end %>
  </div>
  <% unless status == 'Done' %>
    <div class="card-footer">
      <a  href='#createTicket' class='btn btn-secondary' data-toggle="modal" data-target="#create<%= status.parameterize %>Ticket">
        <%= fa_icon("plus") %>
      </a>
      <%= render partial: 'tickets/create_modal', locals: { status: status, project: project} %>
    </div>
  <% end %>
</div>

app/views/tickets/_create_modal.html.erb
<div class="modal text-dark fade" id="create<%= status.parameterize %>Ticket" tabindex="-1" role="dialog" aria-labelledby="create<%= status.parameterize %>TicketLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="create<%= status.parameterize %>TicketLabel">Create a new Ticket</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for :ticket, url: project_sprint_tickets_path(project_id: project.id, sprint_id: project.current_sprint.id) do |f| %>
          <%= f.input :name %>
          <%= f.input :description, as: :text %>
          <%= f.input :hours_of_work %>
          <%= f.input :priority, collection: Ticket::PRIORITIES, default: 'Normal' %>
          <%= f.input :status, input_html: { value: status }, as: :hidden %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tickets/_done_card.html.erb
<div class="row">
  <div class="col-12">
    <a class="card text-white bg-success" href='#recapTicket' data-toggle="modal" data-target="#recapModal<%= ticket.id %>">
      <div class="card-body">
        <div class="card-title">
          <div class="row">
            <div class="col-8">
              <b><%= ticket.name %></b>
            </div>
            <div class="col-3">
              <div class="row">
                <%= render partial: 'tickets/prioritie_badge', locals: { priority: ticket.priority } %>
              </div>
              <div class="row">
                Hours: <%= ticket.hours_of_work %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>

<%= render partial: 'tickets/recap_modal', locals: { ticket: ticket } %>

app/views/tickets/_edit_modal.html.erb
<div class="modal text-dark fade" id="createModal<%= ticket.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel"><%= ticket.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for ticket, url: project_sprint_ticket_path(project_id: ticket.sprint.project.id, sprint_id: ticket.sprint.id, id: ticket.id) do |f| %>
          <%= f.input :name %>
          <%= f.input :description, as: :text %>
          <%= f.input :hours_of_work %>
          <%= f.input :priority, collection: Ticket::PRIORITIES, default: 'Normal' %>
        <div class="row">
          <div class="col-1">
            <%= link_to '<', project_sprint_ticket_previous_path(project_id: ticket.sprint.project.id,
                                                                  sprint_id: ticket.sprint.id,
                                                                  ticket_id: ticket.id),
                                                                  method: :post,
                                                                  class: 'btn btn-dark' %>
          </div>
          <div class="col-1 offset-9">
            <%= link_to '>', project_sprint_ticket_next_path(project_id: ticket.sprint.project.id,
                                                                  sprint_id: ticket.sprint.id,
                                                                  ticket_id: ticket.id),
                                                                  method: :post,
                                                                  class: 'btn btn-dark' %>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.button :submit, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tickets/_prioritie_badge.html.erb
<% case priority
   when 'Critical' %>
  <span class="badge badge-danger">Critical</span>
<% when 'Major' %>
  <span class="badge badge-warning">Major</span>
<% when 'Normal' %>
  <span class="badge badge-info">Normal</span>
<% when 'Low' %>
  <span class="badge badge-primary">Low</span>
<% end %>

app/views/tickets/_qa_card.html.erb
<div class="row">
  <div class="col-12">
    <a class="card text-white bg-secondary" href='#qaTicket' data-toggle="modal" data-target="#qaModal<%= ticket.id %>">
      <div class="card-body">
        <div class="card-title">
          <div class="row">
            <div class="col-8">
              <b><%= ticket.name %></b>
            </div>
            <div class="col-3">
              <div class="row">
                <%= render partial: 'tickets/prioritie_badge', locals: { priority: ticket.priority } %>
              </div>
              <div class="row">
                Hours: <%= ticket.hours_of_work %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </a>
  </div>
</div>

<%= render partial: 'reviews/review_modal', locals: { ticket: ticket } %>

app/views/tickets/_recap_modal.html.erb
<div class="modal text-dark fade" id="recapModal<%= ticket.id %>" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalLabel">Recap</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h5><%= ticket.name %></h5>
        Ticket:
        <ul class="list-group">
          <li class="list-group-item list-group-item-secondary"><b>Name:</b> <%= ticket.name %></li>
          <li class="list-group-item list-group-item-secondary"><b>Description:</b> <%= ticket.description %></li>
          <li class="list-group-item list-group-item-secondary"><b>Hours of work:</b> <%= ticket.hours_of_work %></li>
          <li class="list-group-item list-group-item-secondary"><b>Priority:</b> <%= render partial: 'tickets/prioritie_badge', locals: { priority: ticket.priority } %></li>
        </ul>
        Review:
        <ul class="list-group">
          <li class="list-group-item list-group-item-secondary"><b>Description:</b> <%= ticket.review.last.text %></li>
          <li class="list-group-item list-group-item-secondary"><b><%= ticket.sprint.quality_1 %>:</b> <%= ticket.review.last.quality_1 %></li>
          <li class="list-group-item list-group-item-secondary"><b><%= ticket.sprint.quality_2 %>:</b> <%= ticket.review.last.quality_2 %></li>
          <li class="list-group-item list-group-item-secondary"><b><%= ticket.sprint.quality_3 %>:</b> <%= ticket.review.last.quality_3 %></li>
          <li class="list-group-item list-group-item-secondary"><b><%= ticket.sprint.quality_4 %>:</b> <%= ticket.review.last.quality_4 %></li>
          <li class="list-group-item list-group-item-secondary"><b><%= ticket.sprint.quality_5 %>:</b> <%= ticket.review.last.quality_5 %></li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>